package ru.bmstu.loyaltyapp.config;

public class ActionType {
    public static String MICROSERVICE_DISCOUNT_CURRENT_USER = "MICROSERVICE_DISCOUNT_CURRENT_USER";
    public static String MICROSERVICE_LOYALTY_CURRENT_USER = "MICROSERVICE_LOYALTY_CURRENT_USER";
    public static String MICROSERVICE_PRICE_WITH_DISCOUNT = "MICROSERVICE_PRICE_WITH_DISCOUNT";
    public static String MICROSERVICE_UPDATE_RESERVATION_COUNT = "MICROSERVICE_UPDATE_RESERVATION_COUNT";
    public static String MICROSERVICE_CANCEL_RESERVATION = "MICROSERVICE_CANCEL_RESERVATION";
}