package ru.bmstu.reservationapp.config;

public class ActionType {
    public static String MICROSERVICE_ALL_HOTELS = "MICROSERVICE_ALL_HOTELS";
    public static String MICROSERVICE_HOTEL_BY_ID = "MICROSERVICE_HOTEL_BY_ID";
    public static String MICROSERVICE_HOTEL_BY_UUID = "MICROSERVICE_HOTEL_BY_UUID";
    public static String MICROSERVICE_HOTELID_BY_UUID = "MICROSERVICE_HOTELID_BY_UUID";
    public static String MICROSERVICE_IMAGEURL_BY_HOTELID = "MICROSERVICE_IMAGEURL_BY_HOTELID";
    public static String MICROSERVICE_MOST_POPULAR_HOTELS = "MICROSERVICE_MOST_POPULAR_HOTELS";
    public static String MICROSERVICE_RESERVATION_PRICE = "MICROSERVICE_RESERVATION_PRICE";
    public static String MICROSERVICE_RESERVATION_BY_USERNAME = "MICROSERVICE_RESERVATION_BY_USERNAME";
    public static String MICROSERVICE_RESERVATION_BY_USERNAME_RESERVATIONUID = "MICROSERVICE_RESERVATION_BY_USERNAME_RESERVATIONUID";
    public static String MICROSERVICE_CREATE_RESERVATION = "MICROSERVICE_CREATE_RESERVATION";
    public static String MICROSERVICE_REVOKE_RESERVATION = "MICROSERVICE_REVOKE_RESERVATION";
}