name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
            java-version: 17
            cache: gradle
            
      - name: set up gradle
        uses: gradle/gradle-build-action@v2

      # Reservation
      - name: Grant execute permission for gradlew
        run: cd ReservationApp && chmod +x gradlew
      - name: Build with Gradle
        run: cd ReservationApp && ./gradlew build
        
      # Loyalty
      - name: Grant execute permission for gradlew
        run: cd LoayltyApp && chmod +x gradlew
      - name: Build with Gradle
        run: cd LoayltyApp && ./gradlew build
        
      # Payment
      - name: Grant execute permission for gradlew
        run: cd PaymentApp && chmod +x gradlew
      - name: Build with Gradle
        run: cd PaymentApp && ./gradlew build
        
      # Payment
      - name: Grant execute permission for gradlew
        run: cd Gateway && chmod +x gradlew
      - name: Build with Gradle
        run: cd Gateway && ./gradlew build

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh && chmod +x ./scripts/test-script.sh
        env:
          VARIANT: v2
          SERVICE_NAME: loyaltyapp
          PORT_NUMBER: 8050

      #- uses: education/autograding@v1
      #  id: autograder
      #  continue-on-error: true

      #- name: Github auto grader mark
      #  uses: Romanow/google-sheet-autograder-marker@v1.0
      #  with:
      #    google_token: ${{secrets.GOOGLE_API_KEY}}
      #    sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #    homework_number: 3
      #    user_column: 'D'
      #    column_offset: 'F'
      #    mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
